// <auto-generated />
namespace TransactionManagement.MVC.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class productcrudstarred : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productcrudstarred));
        
        string IMigrationMetadata.Id
        {
            get { return "202009282228578_product crud + starred"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
