// <auto-generated />
namespace TransactionManagement.MVC.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedbacktotalcost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedbacktotalcost));
        
        string IMigrationMetadata.Id
        {
            get { return "202010131954462_added back total cost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
