// <auto-generated />
namespace TransactionManagement.MVC.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class tweaksnmore : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tweaksnmore));
        
        string IMigrationMetadata.Id
        {
            get { return "202010132034256_tweaks n more"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
