// <auto-generated />
namespace TransactionManagement.MVC.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class datetimenowandtotalcostgetter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datetimenowandtotalcostgetter));
        
        string IMigrationMetadata.Id
        {
            get { return "202010121730333_datetime.now and totalcost getter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
